import { useMemo } from "react";
import { Award, History, ShieldCheck, Trophy, Users } from "lucide-react";
import { Link } from "react-router-dom";

import { buildNativeHistoryProjection } from "../../../shared/nativeLeagueIntelligence";
import type { CanonicalLeagueWorkspace } from "../league-domain/types";
import { useNativeCompetition } from "../native-competition/useNativeCompetition";
import { useNativeDraft } from "../native-draft/useNativeDraft";
import { useNativePulse } from "../native-pulse/useNativePulse";
import { useNativeScoring } from "../native-scoring/useNativeScoring";
import { useNativeTrades } from "../native-trades/useNativeTrades";
import { useNativeWaivers } from "../native-waivers/useNativeWaivers";
import "./native-history.css";

function name(id: string, names: Map<string, string>) { return names.get(id) ?? id; }
export function NativeHistoryWorkspace({ workspace }: { workspace: CanonicalLeagueWorkspace }) {
  const season = workspace.season!; const leagueId = workspace.league.id; const pulse = useNativePulse(leagueId); const competition = useNativeCompetition(leagueId, season.id, season.settingsVersionId); const draft = useNativeDraft(leagueId, season.id, season.draftId ?? ""); const waivers = useNativeWaivers(leagueId, season.id, season.settingsVersionId, workspace.membership?.userId ?? "", workspace.authority.canManage); const trades = useNativeTrades(leagueId, season.id, season.settingsVersionId);
  const currentWeek = Math.max(1, ...competition.results.map((result) => result.week)); const scoring = useNativeScoring(leagueId, season.id, currentWeek); const names = useMemo(() => new Map(competition.teams.map((team) => [team.franchiseId, team.name])), [competition.teams]);
  const projection = useMemo(() => buildNativeHistoryProjection({ franchiseIds: competition.teams.map((team) => team.franchiseId), audits: pulse.items.filter((item) => item.sourceType === "audit").map((item) => ({ action: item.title, franchiseIds: item.franchiseIds })), results: competition.results.map((row) => ({ gameId: row.gameId, week: row.week, homeFranchiseId: row.homeFranchiseId, awayFranchiseId: row.awayFranchiseId, homeScore: row.homeScore, awayScore: row.awayScore, homePotentialPoints: row.homePotentialPoints, awayPotentialPoints: row.awayPotentialPoints })), lineups: (scoring.scoringWeek?.lineupTotals ?? []).map((row) => ({ franchiseId: row.franchiseId, week: currentWeek, currentScore: row.currentScore, benchPoints: row.benchPoints, optimalScore: row.optimalScore })), waiverWinningFranchiseIds: waivers.receipts.filter((row) => row.status === "won").map((row) => row.franchiseId), draftFranchiseIds: draft.draft?.selections.map((row) => row.franchiseId) ?? [] }), [competition.results, competition.teams, currentWeek, draft.draft, pulse.items, scoring.scoringWeek, waivers.receipts]);
  const champion = season.phase === "complete" ? competition.standings?.rows.find((row) => row.seed === 1) ?? null : null; const last = season.phase === "complete" ? competition.standings?.rows.at(-1) ?? null : null;
  return <main className="native-history"><header><div><span>Native league history</span><h1>{workspace.league.name} memory</h1><p>Rebuilt from permanent franchises and authoritative native results, drafts, trades, waivers, lineups, scoring projections, and command audits.</p></div><strong>{projection.generatedFrom.auditCount + projection.generatedFrom.resultCount} source events</strong></header>
    <section className="native-history-summary"><article><Trophy aria-hidden="true" /><span>Championship history</span><strong>{champion ? name(champion.franchiseId, names) : "Season in progress"}</strong><small>{champion ? `${season.year} champion` : "Published only after the season completes"}</small></article><article><Award aria-hidden="true" /><span>Hall of Fame</span><strong>{projection.records[0] ? name(projection.records[0].franchiseId, names) : "Awaiting records"}</strong><small>{projection.records[0]?.label ?? "Final native results create record entries"}</small></article><article><History aria-hidden="true" /><span>Last-place archive</span><strong>{last ? name(last.franchiseId, names) : "Season in progress"}</strong><small>{last ? `${season.year} final standing` : "No last-place label before final standings"}</small></article></section>
    <section className="native-history-table" aria-labelledby="career-history-title"><header><Users aria-hidden="true" /><div><span>Career records</span><h2 id="career-history-title">Permanent franchise ledger</h2></div></header><div role="table" aria-label="Native franchise career history"><div role="row" className="is-head"><span>Franchise</span><span>Record</span><span>PF / PA</span><span>Lineup efficiency</span><span>Bench</span><span>Waivers</span><span>Drafted</span></div>{projection.franchiseRows.map((row) => <div role="row" key={row.franchiseId}><strong data-label="Franchise">{name(row.franchiseId, names)}<small>{row.franchiseId}</small></strong><span data-label="Record">{row.wins}-{row.losses}{row.ties ? `-${row.ties}` : ""}</span><span data-label="PF / PA">{row.pointsFor.toFixed(1)} / {row.pointsAgainst.toFixed(1)}</span><span data-label="Lineup efficiency">{row.lineupEfficiency ? `${Math.round(row.lineupEfficiency * 100)}%` : "—"}</span><span data-label="Bench">{row.benchPoints.toFixed(1)}</span><span data-label="Waivers">{row.waiverWins}</span><span data-label="Drafted">{row.draftPicks}</span></div>)}</div></section>
    <div className="native-history-grid"><section><header><span>Rivalries & H2H</span><h2>All native meetings</h2></header>{projection.headToHead.length ? <ol>{projection.headToHead.map((row) => <li key={`${row.franchiseA}-${row.franchiseB}`}><strong>{name(row.franchiseA, names)} vs {name(row.franchiseB, names)}</strong><span>{row.winsA}-{row.winsB}{row.ties ? `-${row.ties}` : ""}</span><small>{row.pointsA.toFixed(1)}–{row.pointsB.toFixed(1)} aggregate points</small></li>)}</ol> : <p>No final native matchups yet.</p>}</section><section><header><span>Records & milestones</span><h2>Automatically rebuilt</h2></header><ol>{projection.records.map((row) => <li key={row.id}><strong>{row.label}</strong><span>{row.value.toFixed(1)}</span><small>{name(row.franchiseId, names)} · Week {row.week}</small></li>)}{projection.milestones.map((row) => <li key={row.id}><strong>{row.label}</strong><small>{name(row.franchiseId, names)}</small></li>)}</ol>{!projection.records.length && !projection.milestones.length ? <p>No threshold has been reached.</p> : null}</section></div>
    <section className="native-history-lineage"><header><ShieldCheck aria-hidden="true" /><div><span>Franchise lineage</span><h2>Identity survives managers and seasonal names</h2></div></header><div>{competition.teams.map((team) => <article key={team.franchiseId}><strong>{team.name}</strong><code>{team.franchiseId}</code><span>{season.year} seasonal team</span><small>Manager accounts are role grants; they do not replace this permanent franchise key.</small></article>)}</div></section>
    <section className="native-history-yearbook"><div><span>{season.year} season yearbook</span><h2>{competition.results.length} final matchups · {trades.receipts.length} trades · {waivers.receipts.filter((row) => row.status === "won").length} waiver awards</h2><p>Weekly recaps, draft history, trade history, waiver efficiency, lineup efficiency, bench points, records, and tendencies are regenerated from the underlying ledger instead of edited summaries.</p></div><Link to={`/league/${leagueId}/pulse`}>Open League Pulse</Link></section>
  </main>;
}
