/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg0: "var(--bg0)",
        bg1: "var(--bg1)",
        panel: "var(--panel)",
        glass: "var(--glass)",
        stroke: "var(--stroke)",
        stroke2: "var(--stroke2)",
        fg0: "var(--fg0)",
        fg1: "var(--fg1)",
        fg2: "var(--fg2)",
        accent: "var(--accent)",
        accent2: "var(--accent2)",
        danger: "var(--danger)",
        success: "var(--success)",
        warning: "var(--warning)",
        // Material Glass Design System
        "bg-0": "var(--bg-0)",
        "bg-1": "var(--bg-1)",
        "bg-2": "var(--bg-2)",
        "text-0": "var(--text-0)",
        "text-1": "var(--text-1)",
        "glass-1": "var(--glass-1)",
        "glass-2": "var(--glass-2)",
        "glass-3": "var(--glass-3)",
        "line-1": "var(--line-1)",
        "spec-1": "var(--spec-1)",
        "spec-2": "var(--spec-2)",
        "accent-1": "var(--accent-1)",
        "accent-2": "var(--accent-2)",
      },
      borderRadius: {
        sm: "var(--r-sm)",
        md: "var(--r-md)",
        lg: "var(--r-lg)",
        xl: "var(--r-xl)",
      },
      boxShadow: {
        s1: "var(--shadow1)",
        s2: "var(--shadow2)",
        s3: "var(--shadow3)",
        "glass-1": "var(--shadow-glass-1)",
        "glass-2": "var(--shadow-glass-2)",
      },
      backdropBlur: {
        sm: "var(--blur-sm)",
        md: "var(--blur-md)",
        lg: "var(--blur-lg)",
      },
    },
  },
  plugins: [],
};
