import { CheckCircle2, GitCompareArrows, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";

import { buildMirrorParityReport, type MirrorParityDimension } from "../../../shared/nativeLeagueIntelligence";
import type { CanonicalLeagueWorkspace } from "../league-domain/types";
import { useNativeCompetition } from "../native-competition/useNativeCompetition";
import { useNativeDraft } from "../native-draft/useNativeDraft";
import { useNativeScoring } from "../native-scoring/useNativeScoring";

function count(metadata: Record<string, unknown>, ...keys: string[]) { for (const key of keys) { const value = Number(metadata[key]); if (Number.isFinite(value)) return value; } return undefined; }
export function CommissionerSafetyPanel({ workspace }: { workspace: CanonicalLeagueWorkspace }) {
  const season = workspace.season!; const competition = useNativeCompetition(workspace.league.id, season.id, season.settingsVersionId); const draft = useNativeDraft(workspace.league.id, season.id, season.draftId ?? ""); const currentWeek = Math.max(1, ...competition.results.map((row) => row.week)); const scoring = useNativeScoring(workspace.league.id, season.id, currentWeek); const metadata = workspace.connection?.importMetadata ?? {};
  const external = Object.fromEntries((["identity", "settings", "rosters", "drafts", "history", "scoring"] as const).flatMap((dimension) => { const keys: Record<typeof dimension, string[]> = { identity: ["franchiseCount", "franchise_count"], settings: ["settingsCount", "settings_count"], rosters: ["rosterPlayerCount", "roster_player_count"], drafts: ["draftPickCount", "draft_pick_count"], history: ["historyGameCount", "history_game_count"], scoring: ["scoringEventCount", "scoring_event_count"] }; const value = count(metadata, ...keys[dimension]); return value === undefined ? [] : [[dimension, value]]; })) as Partial<Record<MirrorParityDimension["dimension"], number>>;
  const native = { identity: competition.teams.length, settings: season.settingsVersionId ? 1 : 0, rosters: competition.teams.reduce((sum, team) => sum + team.rosterPlayerIds.length, 0), drafts: draft.draft?.selections.length ?? 0, history: competition.results.length, scoring: scoring.scoringWeek?.eventCount ?? 0 };
  const parity = buildMirrorParityReport({ authorityMode: workspace.league.authorityMode, external, native }); const base = `/league/${workspace.league.id}`;
  return <div className="commissioner-safety"><section><header><ShieldCheck aria-hidden="true" /><div><span>Commissioner Safe Mode</span><h2>Preview, reason, restore point, receipt</h2></div></header><div className="commissioner-safety-row is-head"><span>Operation</span><span>Impact preview</span><span>Required reason</span><span>Restore / correction</span><span>Audit receipt</span></div>{[
    ["Roster edits", "Roster and lock diff", "Material corrections", "Inverse transaction"], ["Score changes", "Standing rebuild", "Every correction", "Immutable score revision"], ["Schedule changes", "Conflict validation", "Every manual edit", "Prior schedule version"], ["Playoff edits", "Field and bye graph", "Manual qualifiers", "Prior bracket version"], ["Waiver corrections", "Claim outcome receipt", "Commissioner processing", "Roster transaction reversal"], ["Trade reversals", "Two-team asset effects", "Every reversal", "Inverse transaction"], ["Membership changes", "Role and team impact", "Removal / revoke", "New invitation or grant"], ["Scoring changes", "Complete rule impact", "New published version", "Prior settings version"],
  ].map(([operation, impact, reason, restore]) => <div className="commissioner-safety-row" key={operation}><strong>{operation}</strong><span>{impact}</span><span>{reason}</span><span>{restore}</span><span><CheckCircle2 aria-label="Enabled" />Immutable</span></div>)}</section>
    <section><header><GitCompareArrows aria-hidden="true" /><div><span>Mirror & migrate</span><h2>Authority and parity report</h2></div></header><p>Counts compare the external import manifest with native read models. Missing evidence stays unavailable; a matching count does not silently transfer authority.</p><div className="commissioner-parity-head"><span>Dimension</span><span>External</span><span>Native</span><span>Status</span><span>Authority</span></div>{parity.map((row) => <div className="commissioner-parity-row" key={row.dimension}><strong>{row.dimension}</strong><span>{row.externalCount ?? "—"}</span><span>{row.nativeCount ?? "—"}</span><span className={`is-${row.status}`}>{row.status}</span><span>{row.authority}</span><small>{row.detail}</small></div>)}<footer><Link to={`${base}/history`}>Inspect native history</Link><Link to={`${base}/commissioner/audit`}>Open audit receipts</Link></footer></section></div>;
}
