import { collection, limit, onSnapshot, orderBy, query, type DocumentData, type QuerySnapshot } from "firebase/firestore";

import { auditToPulseItem, type NativePulseCategory, type NativePulseItem } from "../../../shared/nativeLeagueIntelligence";
import { firestore } from "../../lib/firebase";
import type { AuditEvent } from "../league-domain/types";
import { normalizeAuditEvent } from "../league-membership/leaguePeople";

export type StoredPulseEvent = NativePulseItem & { body: string; createdBy: string; pollOptions: string[]; revision: number };
export type PulseReaction = { id: string; eventId: string; userId: string; reaction: "like" | "celebrate" | "insightful" | "question"; revision: number; updatedAt: string };
export type PulseComment = { id: string; eventId: string; userId: string; body: string; createdAt: string; revision: number };
export type RuleProposal = { id: string; currentLanguage: string; proposedLanguage: string; effectiveSeason: number; votingThreshold: number; opensAt: string; closesAt: string; votes: Record<string, "yes" | "no" | "abstain">; result: "open" | "passed" | "rejected"; commissionerExplanation: string; createdBy: string; createdAt: string; updatedAt: string; revision: number; voteSummary: { eligible: number; yes: number; no: number; abstain: number; requiredYes: number } | null };

function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function numberValue(value: unknown, fallback = 0) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function strings(value: unknown) { return Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === "string") : []; }

function category(kind: string): NativePulseCategory { return kind === "chat" ? "chat" : kind === "poll" ? "polls" : kind === "lineup_reminder" ? "lineups" : kind === "trade_block_change" ? "trades" : "commissioner"; }
function normalizeEvent(data: DocumentData, id: string): StoredPulseEvent | null { const kind = text(data.kind); const title = text(data.title); if (!title || !kind) return null; return { id, category: category(kind), occurredAt: text(data.created_at), title, body: text(data.body), sourceType: "pulse_event", sourceId: text(data.source_id) || id, automated: data.automated === true, week: data.week === null || data.week === undefined ? null : numberValue(data.week), franchiseIds: strings(data.franchise_ids), createdBy: text(data.created_by), pollOptions: strings(data.poll_options), revision: Math.max(1, numberValue(data.revision, 1)) }; }
function normalizeReaction(data: DocumentData, id: string): PulseReaction | null { const reaction = text(data.reaction); if (!data.active || !["like", "celebrate", "insightful", "question"].includes(reaction)) return null; return { id, eventId: text(data.event_id), userId: text(data.user_id), reaction: reaction as PulseReaction["reaction"], revision: Math.max(1, numberValue(data.revision, 1)), updatedAt: text(data.updated_at) }; }
function normalizeComment(data: DocumentData, id: string): PulseComment | null { const body = text(data.body); return body ? { id, eventId: text(data.event_id), userId: text(data.user_id), body, createdAt: text(data.created_at), revision: Math.max(1, numberValue(data.revision, 1)) } : null; }
function normalizeProposal(data: DocumentData, id: string): RuleProposal | null { const currentLanguage = text(data.current_language); const proposedLanguage = text(data.proposed_language); const result = text(data.result); if (!currentLanguage || !proposedLanguage || !["open", "passed", "rejected"].includes(result)) return null; const votes = Object.fromEntries(Object.entries(record(data.votes)).filter(([, vote]) => ["yes", "no", "abstain"].includes(text(vote))).map(([userId, vote]) => [userId, text(vote) as "yes" | "no" | "abstain"])); const summary = record(data.vote_summary); return { id, currentLanguage, proposedLanguage, effectiveSeason: numberValue(data.effective_season), votingThreshold: numberValue(data.voting_threshold, .5), opensAt: text(data.opens_at), closesAt: text(data.closes_at), votes, result: result as RuleProposal["result"], commissionerExplanation: text(data.commissioner_explanation), createdBy: text(data.created_by), createdAt: text(data.created_at), updatedAt: text(data.updated_at), revision: Math.max(1, numberValue(data.revision, 1)), voteSummary: Object.keys(summary).length ? { eligible: numberValue(summary.eligible), yes: numberValue(summary.yes), no: numberValue(summary.no), abstain: numberValue(summary.abstain), requiredYes: numberValue(summary.required_yes) } : null }; }

type Listener<T> = { value: (rows: T[]) => void; error: (error: Error) => void };
function listen<T>(path: [string, string, string], normalizer: (data: DocumentData, id: string) => T | null, listener: Listener<T>, field: string, count = 100) { return onSnapshot(query(collection(firestore, path[0], path[1], path[2]), orderBy(field, "desc"), limit(count)), (snapshot) => listener.value(snapshot.docs.map((document) => normalizer(document.data(), document.id)).filter((row): row is T => Boolean(row))), (error) => listener.error(error)); }
export function subscribePulseEvents(leagueId: string, listener: Listener<StoredPulseEvent>) { return listen(["leagues", leagueId, "pulseEvents"], normalizeEvent, listener, "created_at"); }
export function subscribePulseReactions(leagueId: string, listener: Listener<PulseReaction>) { return listen(["leagues", leagueId, "pulseReactions"], normalizeReaction, listener, "updated_at", 300); }
export function subscribePulseComments(leagueId: string, listener: Listener<PulseComment>) { return listen(["leagues", leagueId, "pulseComments"], normalizeComment, listener, "created_at", 300); }
export function subscribeRuleProposals(leagueId: string, listener: Listener<RuleProposal>) { return listen(["leagues", leagueId, "ruleProposals"], normalizeProposal, listener, "created_at"); }
export function subscribeAuditPulse(leagueId: string, listener: Listener<NativePulseItem>) { return onSnapshot(query(collection(firestore, "leagues", leagueId, "auditEvents"), orderBy("timestamp", "desc"), limit(200)), (snapshot: QuerySnapshot<DocumentData>) => { const audits = snapshot.docs.map((document) => normalizeAuditEvent(document.data(), leagueId)).filter((entry): entry is AuditEvent => Boolean(entry)).filter((entry) => !/^(pulse_|rule_proposal)/u.test(entry.action)); listener.value(audits.map((entry) => auditToPulseItem({ id: entry.id, action: entry.action, timestamp: entry.timestamp, publicSummary: entry.publicSummary, target: entry.target, actorUserId: entry.actorUserId }))); }, (error) => listener.error(error)); }
