import { describe, expect, it } from "vitest";

import type { LeagueCommand } from "../../shared/leagueCommandProtocol";
import { createRedraftLeagueSettings } from "../../shared/leagueSettings";
import { executeLeagueCommand } from "../../server/league-commands/executeLeagueCommand";
import { LeagueCommandMemoryStore } from "./helpers/leagueCommandMemoryStore";

const leagueId = "d1111111-1111-4111-8111-111111111111"; const seasonId = "d2222222-2222-4222-8222-222222222222"; const commissionerId = "competition-commissioner"; let sequence = 0; function id() { sequence += 1; return `d5000000-0000-4000-8000-${String(sequence).padStart(12, "0")}`; }
function seed() { const store = new LeagueCommandMemoryStore(); const settings = createRedraftLeagueSettings("America/New_York"); settings.teamCount = 5; settings.schedule.regularSeasonWeeks = 5; settings.schedule.playoffTeams = 4; settings.schedule.medianOpponent = true; settings.schedule.allPlay = true; settings.transactions.tradeDeadlineWeek = 5; store.seed(`leagues/${leagueId}`, { id: leagueId, authority_mode: "native", current_season_id: seasonId }); store.seed(`leagues/${leagueId}/seasons/${seasonId}`, { id: seasonId, revision: 1, settings_version_id: "settings-live" }); store.seed(`leagues/${leagueId}/settingsVersions/settings-live`, { status: "published", settings }); const grantId = `${commissionerId}__commissioner`; store.seed(`leagues/${leagueId}/memberships/${commissionerId}`, { user_id: commissionerId, status: "active", role_grant_ids: [grantId] }); store.seed(`leagues/${leagueId}/roleGrants/${grantId}`, { user_id: commissionerId, role: "commissioner", effective_at: "2026-01-01T00:00:00.000Z", expires_at: "", revoked_at: "" }); for (let index = 1; index <= 5; index += 1) { const teamId = `team-${index}`; store.seed(`leagues/${leagueId}/seasons/${seasonId}/seasonTeams/${teamId}`, { id: teamId, franchise_id: teamId, name: `Team ${index}`, division_id: index <= 3 ? "east" : "west", status: "active" }); store.seed(`leagues/${leagueId}/seasons/${seasonId}/waiverTeamStates/${teamId}`, { franchise_id: teamId, standings_rank: index, revision: 1 }); } return store; }
async function execute<T extends LeagueCommand["commandType"]>(store: LeagueCommandMemoryStore, command: LeagueCommand<T>, processedAt: string) { return executeLeagueCommand({ commandValue: command, actorUserId: commissionerId, store, processedAt }); }

describe("native competition commands", () => {
  it("versions schedule generation, standings/results, corrections, and playoffs with audits", async () => {
    const store = seed(); const generated = await execute(store, { commandId: id(), commandType: "generate_native_schedule", actorUserId: commissionerId, leagueId, seasonId, expectedRevision: 1, payload: { settingsVersionId: "settings-live", expectedScheduleRevision: 0, seed: "auditable-seed", protectedMatchups: [{ week: 1, homeFranchiseId: "team-1", awayFranchiseId: "team-2", rivalry: true }], scheduledByes: {} }, reason: "Generate deterministic native schedule", clientCreatedAt: "2026-09-03T01:00:00.000Z" }, "2026-09-03T01:00:01.000Z");
    expect(generated.result).toMatchObject({ scheduleRevision: 1 }); const schedule = store.read(`leagues/${leagueId}/seasons/${seasonId}/schedule/current`)!; expect(schedule).toMatchObject({ revision: 1, seed: "auditable-seed", settings_version_id: "settings-live" }); expect(store.read(`leagues/${leagueId}/seasons/${seasonId}`)).toMatchObject({ revision: 2, schedule_version_id: expect.stringContaining("schedule-") });
    const games = (schedule.games as Array<Record<string, unknown>>).filter((game) => game.week === 1 && game.away_franchise_id); const results = games.map((game, index) => ({ gameId: String(game.id), week: 1, homeFranchiseId: String(game.home_franchise_id), awayFranchiseId: String(game.away_franchise_id), homeScore: 120 - index * 10, awayScore: 80 + index * 5, homePotentialPoints: 130 - index * 10, awayPotentialPoints: 90 + index * 5, status: "final" as const }));
    const rebuilt = await execute(store, { commandId: id(), commandType: "record_native_matchup_results", actorUserId: commissionerId, leagueId, seasonId, expectedRevision: 2, payload: { settingsVersionId: "settings-live", expectedStandingsRevision: 0, results }, reason: "Record completed Week 1 results", clientCreatedAt: "2026-09-03T02:00:00.000Z" }, "2026-09-03T02:00:01.000Z"); expect(rebuilt.result).toMatchObject({ standingsRevision: 1, resultCount: games.length }); const standings = store.read(`leagues/${leagueId}/seasons/${seasonId}/standings/current`)!; expect(standings).toMatchObject({ revision: 1, rows: expect.arrayContaining([expect.objectContaining({ seed: 1, explanation: expect.arrayContaining([expect.stringContaining("published tiebreak")]) })]) });
    const changed = [{ ...results[0]!, homeScore: results[0]!.homeScore + 1 }]; await execute(store, { commandId: id(), commandType: "record_native_matchup_results", actorUserId: commissionerId, leagueId, seasonId, expectedRevision: 3, payload: { settingsVersionId: "settings-live", expectedStandingsRevision: 1, results: changed }, reason: "Correct official Week 1 score", clientCreatedAt: "2026-09-03T03:00:00.000Z" }, "2026-09-03T03:00:01.000Z"); expect(store.paths().some((path) => path.includes("/matchupResultRevisions/"))).toBe(true); expect(store.read(`leagues/${leagueId}/seasons/${seasonId}/matchupResults/${changed[0]!.gameId}`)).toMatchObject({ status: "corrected", correction_reason: "Correct official Week 1 score" });
    const bracket = await execute(store, { commandId: id(), commandType: "build_native_playoffs", actorUserId: commissionerId, leagueId, seasonId, expectedRevision: 4, payload: { settingsVersionId: "settings-live", expectedBracketRevision: 0, startWeek: 6, manualQualifierIds: [] }, reason: "Build native playoff bracket", clientCreatedAt: "2026-09-03T04:00:00.000Z" }, "2026-09-03T04:00:01.000Z"); expect(bracket.result).toMatchObject({ qualifierCount: 4 }); expect(store.read(`leagues/${leagueId}/seasons/${seasonId}/playoffBrackets/current`)).toMatchObject({ revision: 1, games: expect.any(Array), settings_version_id: "settings-live" }); expect(store.paths().filter((path) => path.includes("/auditEvents/")).length).toBe(4);
  });

  it("rejects a manual edit that creates a duplicate same-week game", async () => {
    const store = seed(); await execute(store, { commandId: id(), commandType: "generate_native_schedule", actorUserId: commissionerId, leagueId, seasonId, expectedRevision: 1, payload: { settingsVersionId: "settings-live", expectedScheduleRevision: 0, seed: "edit", protectedMatchups: [], scheduledByes: {} }, reason: "Generate deterministic native schedule", clientCreatedAt: "2026-09-03T01:00:00.000Z" }, "2026-09-03T01:00:01.000Z"); const schedule = store.read(`leagues/${leagueId}/seasons/${seasonId}/schedule/current`)!; const games = schedule.games as Array<Record<string, unknown>>; const duplicate = { ...games.find((game) => game.away_franchise_id)!, id: "manual-duplicate" };
    await expect(execute(store, { commandId: id(), commandType: "save_native_schedule", actorUserId: commissionerId, leagueId, seasonId, expectedRevision: 2, payload: { settingsVersionId: "settings-live", expectedScheduleRevision: 1, games: [...games, duplicate] as never }, reason: "Test duplicate schedule rejection", clientCreatedAt: "2026-09-03T02:00:00.000Z" }, "2026-09-03T02:00:01.000Z")).rejects.toMatchObject({ code: "invalid_schedule" });
  });
});
