// @vitest-environment jsdom

import { fireEvent, render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { describe, expect, it, vi } from "vitest";

import { NativeHistoryWorkspace } from "../features/native-history/NativeHistoryWorkspace";
import { NativeLeaguePulseWorkspace } from "../features/native-pulse/NativeLeaguePulseWorkspace";
import type { CanonicalLeagueWorkspace } from "../features/league-domain/types";

const mocks = vi.hoisted(() => ({ command: vi.fn(async () => ({ result: {}, resultingRevision: 2 })) }));
vi.mock("../features/league-domain/leagueCommands", () => ({ publishPulseEventCommand: mocks.command, reactToPulseEventCommand: mocks.command, commentOnPulseEventCommand: mocks.command, createRuleProposalCommand: mocks.command, voteRuleProposalCommand: mocks.command }));
vi.mock("../features/native-pulse/useNativePulse", () => ({ useNativePulse: () => ({ status: "ready", message: "ready", items: [{ id: "pulse-chat", category: "chat", occurredAt: "2026-09-03T10:00:00.000Z", title: "Sunday plans", body: "Who needs a late swap?", sourceType: "pulse_event", sourceId: "chat-1", automated: false, week: 1, franchiseIds: [] }, { id: "audit-trade", category: "trades", occurredAt: "2026-09-03T09:00:00.000Z", title: "Trade completed", body: "Recorded by the ledger.", sourceType: "audit", sourceId: "audit-1", automated: true, week: null, franchiseIds: ["one", "two"] }], reactions: [{ id: "r1", eventId: "pulse-chat", userId: "manager", reaction: "like", revision: 1, updatedAt: "" }], comments: [{ id: "c1", eventId: "pulse-chat", userId: "other", body: "Lineup ready.", createdAt: "", revision: 1 }], proposals: [{ id: "proposal-one", currentLanguage: "Four playoff teams qualify.", proposedLanguage: "Six playoff teams qualify.", effectiveSeason: 2027, votingThreshold: .67, opensAt: "2026-09-01T00:00:00.000Z", closesAt: "2026-09-10T00:00:00.000Z", votes: {}, result: "open", commissionerExplanation: "Expand the field.", createdBy: "manager", createdAt: "2026-09-02T00:00:00.000Z", updatedAt: "2026-09-02T00:00:00.000Z", revision: 1, voteSummary: null }] }) }));
vi.mock("../features/native-competition/useNativeCompetition", () => ({ useNativeCompetition: () => ({ status: "ready", message: "ready", settings: null, teams: [{ franchiseId: "one", name: "Sunday Best", rosterPlayerIds: ["p1"], rosterRevision: 1 }, { franchiseId: "two", name: "Fourth Down", rosterPlayerIds: ["p2"], rosterRevision: 1 }], schedule: { games: [{ id: "game-1", week: 1, homeFranchiseId: "one", awayFranchiseId: "two", kind: "rivalry" }] }, results: [{ gameId: "game-1", week: 1, homeFranchiseId: "one", awayFranchiseId: "two", homeScore: 130, awayScore: 110, homePotentialPoints: 140, awayPotentialPoints: 125, status: "final", revision: 1, updatedAt: "2026-09-03T08:00:00.000Z" }], standings: { rows: [{ franchiseId: "one", seed: 1 }, { franchiseId: "two", seed: 2 }] }, playoffs: null }) }));
vi.mock("../features/native-scoring/useNativeScoring", () => ({ useNativeScoring: () => ({ status: "ready", message: "ready", scoringWeek: { eventCount: 4, leadChanges: [{ matchupId: "game-1", eventKey: "event-1", occurredAt: "2026-09-03T07:00:00.000Z", leaderFranchiseId: "one", homeScore: 14, awayScore: 10 }], lineupTotals: [{ franchiseId: "one", currentScore: 130, benchPoints: 22, optimalScore: 140 }] } }) }));
vi.mock("../features/native-draft/useNativeDraft", () => ({ useNativeDraft: () => ({ status: "ready", message: "ready", draft: { selections: [{ franchiseId: "one" }, { franchiseId: "two" }] }, teams: [] }) }));
vi.mock("../features/native-waivers/useNativeWaivers", () => ({ useNativeWaivers: () => ({ status: "ready", message: "ready", receipts: [{ status: "won", franchiseId: "one" }] }) }));
vi.mock("../features/native-trades/useNativeTrades", () => ({ useNativeTrades: () => ({ status: "ready", message: "ready", receipts: [{ id: "trade-1" }] }) }));

const workspace: CanonicalLeagueWorkspace = { league: { id: "league-1", name: "Native League", abbreviation: "NL", logoUrl: null, colors: { primary: "", secondary: "" }, timezone: "America/New_York", status: "active", currentSeasonId: "season-1", createdBy: "manager", createdAt: "", updatedAt: "", revision: 1, authorityMode: "native", migrationState: "canonical_active" }, season: { id: "season-1", leagueId: "league-1", year: 2026, phase: "regular_season", revision: 8, settingsVersionId: "settings-1", draftSettingsVersionId: "settings-1", draftId: "draft-1", scheduleVersionId: "v1", startAt: null, endAt: null, legacySourceLeagueId: null }, membership: { leagueId: "league-1", userId: "manager", status: "active", joinedAt: "", revision: 1, roleGrantIds: ["manager__commissioner"], displayName: "Manager", email: "manager@example.com" }, roleGrants: [{ id: "manager__commissioner", leagueId: "league-1", userId: "manager", role: "commissioner", franchiseId: null, permissions: [], effectiveAt: "", expiresAt: null, grantedBy: "manager", revokedAt: null, revision: 1 }], connection: null, authority: { label: "Native GameHQ League — read/write", mode: "native", canRead: true, canManage: true, canSaveLineup: true, permissions: [], roles: ["commissioner"], source: "gamehq" } };

describe("Phase 11 native Pulse and history UI", () => {
  it("filters the combined stream and exposes formal votes and audited publishing", () => {
    render(<MemoryRouter><NativeLeaguePulseWorkspace workspace={workspace} /></MemoryRouter>);
    expect(screen.getByRole("heading", { name: "One league stream" })).toBeTruthy(); expect(screen.getByText("Sunday plans")).toBeTruthy(); expect(screen.getByText(/Rivalry milestone/iu)).toBeTruthy(); expect(screen.getByText("Lineup ready.")).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "Trades" })); expect(screen.queryByText("Sunday plans")).toBeNull(); expect(screen.getByText("Trade completed")).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "All" })); fireEvent.click(screen.getByRole("button", { name: "Yes" })); expect(mocks.command).toHaveBeenCalledWith(expect.objectContaining({ payload: { proposalId: "proposal-one", vote: "yes" } }));
    fireEvent.change(screen.getByLabelText("Title"), { target: { value: "League check-in" } }); fireEvent.change(screen.getByLabelText("Message"), { target: { value: "Set your lineups." } }); fireEvent.click(screen.getByRole("button", { name: "Publish" })); expect(mocks.command).toHaveBeenCalledWith(expect.objectContaining({ payload: expect.objectContaining({ kind: "chat", title: "League check-in" }) }));
  }, 15_000);

  it("renders permanent franchise history separately from manager identity", () => {
    render(<MemoryRouter><NativeHistoryWorkspace workspace={workspace} /></MemoryRouter>);
    expect(screen.getByRole("heading", { name: "Native League memory" })).toBeTruthy(); expect(screen.getByRole("heading", { name: "Permanent franchise ledger" })).toBeTruthy(); expect(screen.getAllByText("Highest single-week score").length).toBeGreaterThan(0); expect(screen.getAllByText("Sunday Best").length).toBeGreaterThan(0); expect(screen.getAllByText(/Manager accounts are role grants/iu).length).toBe(2);
  });
});
