import { collection, doc, onSnapshot, type Unsubscribe } from "firebase/firestore";

import { firestore } from "../../lib/firebase";
import type { NativeMatchupResult, NativePlayoffBracket, NativePlayoffGame, NativeSchedule, NativeScheduleGame, NativeStandingRow, NativeStandings } from "../league-domain/types";

function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function text(value: unknown) { return typeof value === "string" ? value.trim() : ""; }
function numberValue(value: unknown) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
function whole(value: unknown) { return Math.round(numberValue(value)); }
function strings(value: unknown) { return Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === "string") : []; }
function records(value: unknown) { return Array.isArray(value) ? value.map(record) : []; }

function normalizeGame(value: unknown): NativeScheduleGame | null { const data = record(value); const id = text(data.id); const kind = text(data.kind); const homeFranchiseId = text(data.home_franchise_id); if (!id || !homeFranchiseId || !["regular", "rivalry", "protected", "bye"].includes(kind)) return null; return { id, week: whole(data.week), slot: whole(data.slot), homeFranchiseId, awayFranchiseId: text(data.away_franchise_id) || null, kind: kind as NativeScheduleGame["kind"], twoWeekSeriesId: text(data.two_week_series_id), divisionGame: Boolean(data.division_game), conferenceGame: Boolean(data.conference_game) }; }
export function normalizeNativeSchedule(value: unknown): NativeSchedule | null { const data = record(value); const revision = whole(data.revision); if (revision < 1) return null; return { revision, versionId: text(data.version_id), settingsVersionId: text(data.settings_version_id), seed: text(data.seed), source: text(data.source) === "manual" ? "manual" : "generated", games: records(data.games).map(normalizeGame).filter((entry): entry is NativeScheduleGame => Boolean(entry)), validationIssues: records(data.validation_issues).map((row) => ({ code: text(row.code), severity: text(row.severity) === "error" ? "error" as const : "warning" as const, message: text(row.message) })), generatedAt: text(data.generated_at), editedAt: text(data.edited_at), updatedAt: text(data.updated_at) }; }
function normalizeStanding(value: unknown): NativeStandingRow | null { const data = record(value); const franchiseId = text(data.franchise_id); if (!franchiseId) return null; const state = text(data.state); return { franchiseId, seed: whole(data.seed), wins: whole(data.wins), losses: whole(data.losses), ties: whole(data.ties), winningPercentage: numberValue(data.winning_percentage), divisionWins: whole(data.division_wins), divisionLosses: whole(data.division_losses), divisionTies: whole(data.division_ties), divisionPercentage: numberValue(data.division_percentage), medianWins: whole(data.median_wins), medianLosses: whole(data.median_losses), medianTies: whole(data.median_ties), allPlayWins: whole(data.all_play_wins), allPlayLosses: whole(data.all_play_losses), allPlayTies: whole(data.all_play_ties), allPlayPercentage: numberValue(data.all_play_percentage), pointsFor: numberValue(data.points_for), pointsAgainst: numberValue(data.points_against), potentialPoints: numberValue(data.potential_points), lineupEfficiency: numberValue(data.lineup_efficiency), streak: text(data.streak), remainingScheduleStrength: numberValue(data.remaining_schedule_strength), playoffProbability: numberValue(data.playoff_probability), state: (["clinched", "eliminated"].includes(state) ? state : "alive") as NativeStandingRow["state"], explanation: strings(data.explanation) }; }
export function normalizeNativeStandings(value: unknown): NativeStandings | null { const data = record(value); const revision = whole(data.revision); if (revision < 1) return null; return { revision, scheduleVersionId: text(data.schedule_version_id), settingsVersionId: text(data.settings_version_id), completedResultCount: whole(data.completed_result_count), rows: records(data.rows).map(normalizeStanding).filter((entry): entry is NativeStandingRow => Boolean(entry)).sort((a, b) => a.seed - b.seed), updatedAt: text(data.updated_at) }; }
function normalizePlayoffGame(value: unknown): NativePlayoffGame | null { const data = record(value); const id = text(data.id); const bracket = text(data.bracket); if (!id || !["championship", "consolation", "toilet"].includes(bracket)) return null; return { id, bracket: bracket as NativePlayoffGame["bracket"], round: whole(data.round), startWeek: whole(data.start_week), endWeek: whole(data.end_week), highSeed: data.high_seed === null ? null : whole(data.high_seed), lowSeed: data.low_seed === null ? null : whole(data.low_seed), homeFranchiseId: text(data.home_franchise_id) || null, awayFranchiseId: text(data.away_franchise_id) || null, advancesTo: text(data.advances_to) || null, loserAdvances: Boolean(data.loser_advances) }; }
export function normalizeNativePlayoffBracket(value: unknown): NativePlayoffBracket | null { const data = record(value); const revision = whole(data.revision); if (revision < 1) return null; return { revision, standingsRevision: whole(data.standings_revision), settingsVersionId: text(data.settings_version_id), qualifiers: strings(data.qualifiers), byeSeeds: Array.isArray(data.bye_seeds) ? data.bye_seeds.map(whole) : [], reseeding: Boolean(data.reseeding), roundWeeks: whole(data.round_weeks), games: records(data.games).map(normalizePlayoffGame).filter((entry): entry is NativePlayoffGame => Boolean(entry)), correctionReason: text(data.correction_reason), updatedAt: text(data.updated_at) }; }
export function normalizeMatchupResult(value: unknown): NativeMatchupResult | null { const data = record(value); const gameId = text(data.game_id); if (!gameId) return null; return { gameId, week: whole(data.week), homeFranchiseId: text(data.home_franchise_id), awayFranchiseId: text(data.away_franchise_id), homeScore: numberValue(data.home_score), awayScore: numberValue(data.away_score), homePotentialPoints: numberValue(data.home_potential_points), awayPotentialPoints: numberValue(data.away_potential_points), status: text(data.status) === "corrected" ? "corrected" : "final", correctionReason: text(data.correction_reason), revision: whole(data.revision), updatedAt: text(data.updated_at) }; }
type Handlers<T> = { value: (value: T) => void; error: (error: Error) => void }; function errorValue(value: unknown) { return value instanceof Error ? value : new Error(String(value)); }
export function subscribeSchedule(leagueId: string, seasonId: string, handlers: Handlers<NativeSchedule | null>): Unsubscribe { return onSnapshot(doc(firestore, "leagues", leagueId, "seasons", seasonId, "schedule", "current"), (snapshot) => handlers.value(snapshot.exists() ? normalizeNativeSchedule(snapshot.data()) : null), (error) => handlers.error(errorValue(error))); }
export function subscribeStandings(leagueId: string, seasonId: string, handlers: Handlers<NativeStandings | null>): Unsubscribe { return onSnapshot(doc(firestore, "leagues", leagueId, "seasons", seasonId, "standings", "current"), (snapshot) => handlers.value(snapshot.exists() ? normalizeNativeStandings(snapshot.data()) : null), (error) => handlers.error(errorValue(error))); }
export function subscribePlayoffs(leagueId: string, seasonId: string, handlers: Handlers<NativePlayoffBracket | null>): Unsubscribe { return onSnapshot(doc(firestore, "leagues", leagueId, "seasons", seasonId, "playoffBrackets", "current"), (snapshot) => handlers.value(snapshot.exists() ? normalizeNativePlayoffBracket(snapshot.data()) : null), (error) => handlers.error(errorValue(error))); }
export function subscribeResults(leagueId: string, seasonId: string, handlers: Handlers<NativeMatchupResult[]>): Unsubscribe { return onSnapshot(collection(firestore, "leagues", leagueId, "seasons", seasonId, "matchupResults"), (snapshot) => handlers.value(snapshot.docs.map((entry) => normalizeMatchupResult(entry.data())).filter((entry): entry is NativeMatchupResult => Boolean(entry))), (error) => handlers.error(errorValue(error))); }
