import { useEffect, useState } from "react";

import { parseLeagueSettings, type LeagueSettingsV1 } from "../../../shared/leagueSettings";
import { getSettingsVersion } from "../league-domain/firebaseLeagueRepository";
import type { NativeMatchupResult, NativePlayoffBracket, NativeSchedule, NativeStandings, SeasonTeam } from "../league-domain/types";
import { listNativeDraftTeams } from "../native-draft/nativeDraft";
import { subscribePlayoffs, subscribeResults, subscribeSchedule, subscribeStandings } from "./nativeCompetition";

type State = { status: "loading" | "ready" | "error"; message: string; settings: LeagueSettingsV1 | null; teams: SeasonTeam[]; schedule: NativeSchedule | null; standings: NativeStandings | null; playoffs: NativePlayoffBracket | null; results: NativeMatchupResult[] };
const EMPTY: State = { status: "loading", message: "Loading native competition state…", settings: null, teams: [], schedule: null, standings: null, playoffs: null, results: [] };
export function useNativeCompetition(leagueId: string, seasonId: string, settingsVersionId: string) { const [state, setState] = useState<State>(EMPTY); useEffect(() => { let active = true; setState(EMPTY); const fail = (error: Error) => active && setState((current) => ({ ...current, status: "error", message: error.message })); void Promise.all([listNativeDraftTeams(leagueId, seasonId), getSettingsVersion(leagueId, settingsVersionId)]).then(([teams, version]) => { if (!active) return; const parsed = parseLeagueSettings(version?.settings); setState((current) => parsed.issues.length ? { ...current, status: "error", message: parsed.issues[0]?.message ?? "Published competition settings are unavailable." } : { ...current, status: "ready", message: "Competition state synchronized.", teams, settings: parsed.settings }); }).catch((error) => fail(error instanceof Error ? error : new Error(String(error)))); const subscriptions = [subscribeSchedule(leagueId, seasonId, { value: (schedule) => active && setState((current) => ({ ...current, schedule })), error: fail }), subscribeStandings(leagueId, seasonId, { value: (standings) => active && setState((current) => ({ ...current, standings })), error: fail }), subscribePlayoffs(leagueId, seasonId, { value: (playoffs) => active && setState((current) => ({ ...current, playoffs })), error: fail }), subscribeResults(leagueId, seasonId, { value: (results) => active && setState((current) => ({ ...current, results })), error: fail })]; return () => { active = false; subscriptions.forEach((unsubscribe) => unsubscribe()); }; }, [leagueId, seasonId, settingsVersionId]); return state; }
