import type {
  AuctionValueSource,
  AuctionSourceAccess,
  AuctionSourceType,
  ScoringFormat,
  SourceDirectoryCategory,
  SourceVerificationStatus,
} from "./auctionValueTypes";

const VERIFIED_AT = "2026-08-27";

type SourceInput = {
  id: string;
  name: string;
  shortName?: string;
  sourceType: AuctionSourceType;
  category: SourceDirectoryCategory;
  sourceUrl: string;
  notes: string;
  formats?: ScoringFormat[];
  leagueSizes?: number[];
  defaultLeagueSize?: number;
  budget?: number;
  qbFormat?: AuctionValueSource["qbFormat"];
  access?: AuctionSourceAccess;
  comparisonReady?: boolean;
  printableInsideFFAA?: boolean;
  externalOnly?: boolean;
  sourceUpdatedAt?: string;
  importedAt?: string;
  rosterAssumptions?: string;
  verificationStatus?: SourceVerificationStatus;
};

function source(input: SourceInput): AuctionValueSource {
  const access = input.access ?? "public";
  const comparisonReady = input.comparisonReady ?? false;
  const printableInsideFFAA = input.printableInsideFFAA ?? comparisonReady;

  return {
    id: input.id,
    name: input.name,
    shortName: input.shortName ?? input.name,
    sourceType: input.sourceType,
    category: input.category,
    sourceUrl: input.sourceUrl,
    ...(input.category === "archive" ? {} : { season: 2026 }),
    formats: input.formats ?? [],
    supportedLeagueSizes: input.leagueSizes ?? [],
    ...(input.defaultLeagueSize ? { defaultLeagueSize: input.defaultLeagueSize } : {}),
    ...(input.budget ? { sourceBudget: input.budget } : {}),
    qbFormat: input.qbFormat ?? "unknown",
    access,
    comparisonReady,
    printableInsideFFAA,
    externalOnly: input.externalOnly ?? !printableInsideFFAA,
    ...(access === "registration_required" ? { requiresRegistration: true } : {}),
    ...(access === "partial" ? { partialAccess: true } : {}),
    ...(input.sourceUpdatedAt ? { sourceUpdatedAt: input.sourceUpdatedAt } : {}),
    ...(input.importedAt ? { importedAt: input.importedAt } : {}),
    ...(input.rosterAssumptions ? { rosterAssumptions: input.rosterAssumptions } : {}),
    notes: input.notes,
    verificationStatus: input.verificationStatus ?? "verified",
    verifiedAt: VERIFIED_AT,
  };
}

const currentValueSources: AuctionValueSource[] = [
  source({
    id: "espn",
    name: "ESPN Cheat Sheet Central",
    shortName: "ESPN",
    sourceType: "expert_projection",
    category: "current_values",
    sourceUrl: "https://g.espncdn.com/s/ffldraftkit/26/NFL26_CS_PPR300.pdf?adddata=2026CS_PPR300",
    notes: "Official 2026 PPR 300 PDF imported from the public draft kit.",
    formats: ["ppr"],
    leagueSizes: [10],
    defaultLeagueSize: 10,
    budget: 200,
    qbFormat: "one_qb",
    comparisonReady: true,
    sourceUpdatedAt: "2026-08-10",
    importedAt: "2026-08-10",
    rosterAssumptions: "10 teams, $200 salary cap; PPR draft-kit assumptions.",
  }),
  source({
    id: "sports-illustrated",
    name: "Sports Illustrated",
    shortName: "SI",
    sourceType: "expert_projection",
    category: "current_values",
    sourceUrl: "https://www.si.com/onsi/fantasy/rankings/printable-fantasy-football-auction-draft-cheat-sheet-fair-values-ppr-standard",
    notes: "Public 2026 auction sheet is live for all three formats; the imported August 25 snapshot contains the PPR position tables.",
    formats: ["ppr"],
    budget: 200,
    comparisonReady: true,
    sourceUpdatedAt: "2026-08-25",
    importedAt: "2026-08-25T14:16:50.648Z",
  }),
  source({
    id: "usa-today",
    name: "USA TODAY Auction Values",
    shortName: "USA Today",
    sourceType: "expert_projection",
    category: "current_values",
    sourceUrl: "https://sports.yahoo.com/articles/2026-fantasy-football-rankings-updated-224612057.html",
    notes: "Public syndicated 2026 Top 250 with distinct Standard, Half PPR, and Full PPR auction values.",
    formats: ["standard", "half_ppr", "ppr"],
    leagueSizes: [12],
    defaultLeagueSize: 12,
    budget: 200,
    qbFormat: "one_qb",
    comparisonReady: true,
    sourceUpdatedAt: "2026-08-19",
    importedAt: "2026-08-25T14:16:50.648Z",
    rosterAssumptions: "12 teams, one QB, $200 budget.",
  }),
  source({
    id: "yahoo-sports",
    name: "Yahoo Sports Rankings",
    shortName: "Yahoo Sports",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://sports.yahoo.com/fantasy/topic/rankings/",
    notes: "Current editorial rankings hub; no stable public auction-dollar export is imported.",
    formats: ["ppr"],
  }),
  source({
    id: "cbs-sports",
    name: "CBS Sports Draft Prep",
    shortName: "CBS",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://www.cbssports.com/fantasy/football/rankings/standard/",
    notes: "Public rankings surface; a current, reusable auction-dollar board was not available to import.",
    formats: ["standard"],
  }),
  source({
    id: "fantasypros",
    name: "FantasyPros Dollar Value Calculator",
    shortName: "FPros $",
    sourceType: "custom_calculator",
    category: "current_values",
    sourceUrl: "https://www.fantasypros.com/nfl/auction-values/calculator.php",
    notes: "Public interactive calculator; results depend on league inputs and are not a single canonical board.",
    formats: ["standard", "half_ppr", "ppr"],
    leagueSizes: [8, 10, 12, 14, 16],
    budget: 200,
  }),
  source({
    id: "fantasypros-salary-cap",
    name: "FantasyPros Salary Cap Calculator",
    shortName: "FPros Cap",
    sourceType: "custom_calculator",
    category: "current_values",
    sourceUrl: "https://www.fantasypros.com/nfl/auction-values/calculator.php",
    notes: "League-configurable salary-cap tool; linked externally to preserve its interactive assumptions.",
    formats: ["standard", "half_ppr", "ppr"],
    leagueSizes: [8, 10, 12, 14, 16],
  }),
  source({
    id: "fantasynerds",
    name: "Fantasy Nerds",
    shortName: "FNerds",
    sourceType: "expert_projection",
    category: "current_values",
    sourceUrl: "https://www.fantasynerds.com/nfl/auction?teams=12&budget=200&format=ppr",
    notes: "Only the public top-ten preview is imported; subscriber rows are never requested.",
    formats: ["ppr"],
    leagueSizes: [12],
    defaultLeagueSize: 12,
    budget: 200,
    qbFormat: "one_qb",
    access: "partial",
    comparisonReady: true,
    sourceUpdatedAt: "2026-08-25",
    importedAt: "2026-08-25T14:16:50.648Z",
  }),
  source({
    id: "draftsharks",
    name: "DraftSharks",
    shortName: "DSharks",
    sourceType: "expert_projection",
    category: "current_values",
    sourceUrl: "https://www.draftsharks.com/auction-values",
    notes: "The unauthenticated public top 25 is imported; synced-league and subscriber rows stay external.",
    formats: ["ppr"],
    budget: 200,
    qbFormat: "one_qb",
    access: "partial",
    comparisonReady: true,
    sourceUpdatedAt: "2026-08-27",
    importedAt: "2026-08-25T14:16:50.648Z",
    rosterAssumptions: "Full PPR, $200, 1 QB, 2 RB, 2 WR, 1 TE, 1 FLEX, K and DEF.",
  }),
  source({
    id: "fantasy-life",
    name: "Fantasy Life",
    shortName: "Fantasy Life",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://www.fantasylife.com/fantasy-football-auction-values",
    notes: "Public dynamic board; no stable current export is imported into FFAA.",
  }),
  source({
    id: "rotowire",
    name: "RotoWire",
    shortName: "RotoWire",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://www.rotowire.com/football/auction-values.php",
    notes: "Current customizable auction page; complete values require subscriber access.",
    formats: ["standard", "half_ppr", "ppr"],
    access: "paid",
  }),
  source({
    id: "razzball",
    name: "Razzball",
    shortName: "Razzball",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://football.razzball.com/",
    notes: "Fantasy-football rankings site; no verified current public football auction-value export was found.",
    verificationStatus: "partial",
  }),
  source({
    id: "fftoday",
    name: "FFToday",
    shortName: "FFToday",
    sourceType: "expert_projection",
    category: "current_values",
    sourceUrl: "https://www.fftoday.com/rankings/26-av-ppr.html",
    notes: "Complete public $200 boards imported separately for all three scoring formats.",
    formats: ["standard", "half_ppr", "ppr"],
    leagueSizes: [12],
    defaultLeagueSize: 12,
    budget: 200,
    qbFormat: "one_qb",
    comparisonReady: true,
    sourceUpdatedAt: "2026-08-20",
    importedAt: "2026-08-25T14:16:50.648Z",
    rosterAssumptions: "12 teams, $200, 18 roster spots; 1 QB, 2 RB, 3 WR, 1 TE, K and DEF.",
  }),
  source({
    id: "fftoolbox",
    name: "FullTime Fantasy / FFToolbox",
    shortName: "FFToolbox",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://fftoolbox.fulltimefantasy.com/football/2026/auction-values.cfm",
    notes: "The 2026 draft hub advertises auction values, but no reliable current rows were exposed to the importer.",
    verificationStatus: "partial",
  }),
  source({
    id: "fantasy-six-pack",
    name: "Fantasy Six Pack",
    shortName: "F6P",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://fantasysixpack.net/fantasy-football-auction-values/",
    notes: "Current public 2026 article; values remain external until a permitted stable import is added.",
    sourceUpdatedAt: "2026-08-24",
  }),
  source({
    id: "propsbot",
    name: "PropsBot",
    shortName: "PropsBot",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://propsbot.ai/fantasy-football-auction-values/",
    notes: "Public 2026 half-PPR top-50 board; not yet normalized into the canonical player dataset.",
    formats: ["half_ppr"],
    leagueSizes: [12],
    defaultLeagueSize: 12,
    budget: 200,
    qbFormat: "one_qb",
  }),
  source({
    id: "sharp-football",
    name: "Sharp Football Analysis",
    shortName: "Sharp",
    sourceType: "external_sheet",
    category: "current_values",
    sourceUrl: "https://www.sharpfootballanalysis.com/fantasy-packages/",
    notes: "Auction values are part of the paid 2026 draft-kit package.",
    access: "paid",
  }),
  source({
    id: "sportsbrackets",
    name: "SportsBrackets",
    shortName: "SBrkt",
    sourceType: "community_sheet",
    category: "current_values",
    sourceUrl: "https://sportsbrackets.net/2026/07/24/2026-fantasy-football-auction-values-printable/",
    notes: "Free printable PPR board imported for display; excluded from expert consensus to avoid correlated inputs.",
    formats: ["ppr"],
    leagueSizes: [12],
    defaultLeagueSize: 12,
    budget: 200,
    qbFormat: "one_qb",
    comparisonReady: true,
    sourceUpdatedAt: "2026-07-24",
    importedAt: "2026-08-25T14:16:50.648Z",
  }),
  source({
    id: "football-absurdity",
    name: "Football Absurdity / BeerSheet Generator",
    shortName: "BeerSheet",
    sourceType: "custom_calculator",
    category: "current_values",
    sourceUrl: "https://footballabsurdity.com/beersheet-request-form/",
    notes: "Custom sheet request generator; each result depends on user league settings.",
    formats: ["standard", "half_ppr", "ppr"],
  }),
];

const marketAndToolSources: AuctionValueSource[] = [
  source({ id: "yahoo", name: "Yahoo Salary Cap Draft Analysis", shortName: "Yahoo AAV", sourceType: "market_aav", category: "market_tools", sourceUrl: "https://football.fantasysports.yahoo.com/f1/draftanalysis?type=salcap", notes: "Public shell is reachable, but current player rows are client-rendered and not imported.", budget: 200 }),
  source({ id: "nffc-aav", name: "NFFC Average Auction Values", shortName: "NFFC", sourceType: "market_aav", category: "market_tools", sourceUrl: "https://nfc.shgn.com/", notes: "NFFC contest hub; the former public AAV path is no longer stable, so no reusable export is imported.", verificationStatus: "partial" }),
  source({ id: "rtsports-aav", name: "RT Sports Average Auction Values", shortName: "RT AAV", sourceType: "market_aav", category: "market_tools", sourceUrl: "https://www.freedraftguide.com/football/draft-guide-average-pdf.php?AAV=YES", notes: "248 current market rows are retained locally, but mixed scoring and league assumptions prevent format-specific comparison.", budget: 200, sourceUpdatedAt: "2026-08-25", importedAt: "2026-08-25T14:16:50.648Z", printableInsideFFAA: false }),
  source({ id: "yafsb-aav", name: "YAFSB Sleeper Auction AAV", shortName: "YAFSB", sourceType: "market_aav", category: "market_tools", sourceUrl: "https://yafsb.com/fantasy-football/auction-draft-values/?scoring_type=half_ppr&league_size=12&is_superflex=False&is_dynasty=False&is_rookies=False", notes: "Actual public Sleeper auction prices for 12-team half-PPR, one-QB redraft leagues.", formats: ["half_ppr"], leagueSizes: [12], defaultLeagueSize: 12, budget: 200, qbFormat: "one_qb", comparisonReady: true, sourceUpdatedAt: "2026-08-25", importedAt: "2026-08-25T14:16:50.648Z" }),
  source({ id: "fantasy-football-helper", name: "Fantasy Football Helper Auction Value Edge", shortName: "FF Helper", sourceType: "market_aav", category: "market_tools", sourceUrl: "https://fantasyfootballhelper.com/auction-values/", notes: "Public consensus-price overview; the full platform-specific edge tool is proprietary." }),
  source({ id: "rotoalpha", name: "RotoAlpha", shortName: "RotoAlpha", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://www.rotoalpha.com/tools/auction-values", notes: "Free no-account calculator for custom team counts, budgets, rosters, and all three scoring formats.", formats: ["standard", "half_ppr", "ppr"], leagueSizes: [8, 10, 12, 14, 16] }),
  source({ id: "rubesheets", name: "RubeSheets", shortName: "RubeSheets", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://rubesheets.com/Footballv2.aspx", notes: "Free customizable 2026 calculator; login enables saved features.", formats: ["standard", "half_ppr", "ppr"], leagueSizes: [8, 10, 12, 14, 16] }),
  source({ id: "lineup-experts", name: "LineupExperts", shortName: "LineupExperts", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://www.lineupexperts.com/football/auction-value-generator", notes: "Free configurable generator; registration is required to save and reuse generated sheets.", formats: ["standard", "half_ppr", "ppr"], access: "registration_required" }),
  source({ id: "dlf-auction-app", name: "DLF Dynasty Auction App", shortName: "DLF", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://dynastyleaguefootball.com/2020/04/22/new-dynasty-tool-tutorial-how-to-use-the-dlf-dynasty-startup-auction-app/", notes: "Dynasty startup auction application available to DLF subscribers.", access: "paid" }),
  source({ id: "ryftify", name: "Ryftify", shortName: "Ryftify", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://www.ryftify.com/", notes: "Active-beta fantasy intelligence product with an auction area; no public canonical board is exposed.", access: "partial" }),
  source({ id: "solver-sports", name: "SolverSports Salary-Cap Helper", shortName: "SolverSports", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://solversports.com/", notes: "Tool destination retained as external; a current public football value board was not verified.", verificationStatus: "partial" }),
  source({ id: "letmebet", name: "LetMeBet Auction Draft Calculator", shortName: "LetMeBet", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://letmebet.com/auction-draft-calculator/", notes: "Sleeper-connected real-time calculator; results depend on the selected league." }),
  source({ id: "fantasy-on-draft", name: "Fantasy on Draft Companion", shortName: "FoDraft", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://fantasyondraft.com/", notes: "Draft companion with Standard and PPR values from licensed FantasyData inputs; those values are not republished.", formats: ["standard", "ppr"], access: "partial" }),
  source({ id: "auction-cipher", name: "Auction Cipher", shortName: "Cipher", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://auctioncipher.com/features", notes: "League-history auction tool powered by FantasyPros and nflverse; no public standalone board is imported.", access: "registration_required" }),
  source({ id: "tg-fantasy-baseball", name: "TGFantasyBaseball Football Auction Calculator", shortName: "TG Fantasy", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://tgfantasybaseball.com/", notes: "Legacy tool publisher retained in the directory; a current football calculator URL was not verified.", access: "unavailable", verificationStatus: "unavailable" }),
  source({ id: "faablab", name: "FaaBLab Crowd-Sourced AAV", shortName: "FaaBLab", sourceType: "market_aav", category: "market_tools", sourceUrl: "https://www.faablab.app/auction", notes: "Crowd-sourced auction prices; sample and league assumptions depend on community submissions." }),
  source({ id: "myfantasyleague-aav", name: "MyFantasyLeague Average Auction Values", shortName: "MFL AAV", sourceType: "market_aav", category: "market_tools", sourceUrl: "https://www.myfantasyleague.com/2026/top?L=&SEARCHTYPE=AUCTION", notes: "Platform average-auction surface; current public export reliability was not sufficient for import.", access: "partial" }),
  source({ id: "draftexpert-pro", name: "DraftExpert Pro", shortName: "DraftExpert", sourceType: "custom_calculator", category: "market_tools", sourceUrl: "https://draftexpertpro.com/", notes: "Mobile auction optimizer with a free configurable calculator and paid draft-night application.", formats: ["standard", "half_ppr", "ppr"], access: "partial" }),
];

const communitySources: AuctionValueSource[] = [
  source({ id: "elboberto", name: "ElBoberto Custom Auction Value Generator", shortName: "ElBoberto", sourceType: "community_sheet", category: "community", sourceUrl: "https://www.reddit.com/r/fantasyfootball/comments/1uttmpp/elbobertos_custom_auction_value_generator_2026/", notes: "Free 2026 workbook and web app derived from FantasyPros projections; excluded from consensus to avoid duplicate inputs.", formats: ["standard", "half_ppr", "ppr"] }),
  source({ id: "csg", name: "CSG Fantasy Football Spreadsheets", shortName: "CSG", sourceType: "community_sheet", category: "community", sourceUrl: "https://www.reddit.com/r/fantasyfootball/comments/1vus5wp/csg_fantasy_football_spreadsheet_v141_2026/", notes: "Free 2026 Excel and Google Sheets tools combining several publisher inputs; external to avoid double counting.", formats: ["standard", "half_ppr", "ppr"] }),
  source({ id: "community-live-inflation", name: "2026 Community Auction Spreadsheet with Live Inflation", shortName: "Live Inflation", sourceType: "community_sheet", category: "community", sourceUrl: "https://www.reddit.com/r/fantasyfootball/comments/1voco4n/back_for_2026_my_auction_draft_spreadsheet_tool/", notes: "Community Google Sheet for tiers, historical bids, and live inflation tracking.", formats: ["standard", "half_ppr", "ppr"] }),
  source({ id: "peaks-cheat-sheets", name: "Peak's Fantasy Football Cheat Sheets", shortName: "Peak", sourceType: "community_sheet", category: "community", sourceUrl: "https://peakedinhighskool.com/fantasy-football-cheat-sheets/", notes: "Community cheat-sheet hub; auction values vary by generated sheet." }),
  source({ id: "draftsheets", name: "DraftSheets / BeerSheets Replacement", shortName: "DraftSheets", sourceType: "community_sheet", category: "community", sourceUrl: "https://www.reddit.com/r/fantasyfootball/comments/1vyym6v/2026_draftsheets_beersheets_replacement_updated/", notes: "Current community BeerSheets replacement with configurable snake or auction value output.", formats: ["standard", "half_ppr", "ppr"] }),
  source({ id: "another-draft-sheet", name: "Another Draft Sheet Option", shortName: "ADSO", sourceType: "community_sheet", category: "community", sourceUrl: "https://www.reddit.com/r/fantasyfootball/comments/1vtqp3c/another_draft_sheet_option_08202026/", notes: "Current customizable community sheet with optional auction-value conversion.", formats: ["standard", "half_ppr", "ppr"] }),
  source({ id: "hold-my-beersheets", name: "Hold-My-BeerSheets / TapThatDraft", shortName: "HMB", sourceType: "community_sheet", category: "community", sourceUrl: "https://subvertadown.com/tap-that-draft", notes: "Free one-page generated cheat sheets plus an optional draft companion.", formats: ["standard", "half_ppr", "ppr"], access: "partial" }),
  source({ id: "auction-optimizer-r", name: "Fantasy Football Auction Optimizer in R", shortName: "R Optimizer", sourceType: "community_sheet", category: "community", sourceUrl: "https://github.com/gseacat/fantasy-football-auction-optimizer", notes: "Open-source optimizer that requires user-supplied projections and league assumptions." }),
  source({ id: "jbarciauskas-ffauction", name: "jbarciauskas/ffauction", shortName: "ffauction", sourceType: "community_sheet", category: "community", sourceUrl: "https://github.com/jbarciauskas/ffauction", notes: "Open-source auction project; repository availability was not confirmed by search indexing.", verificationStatus: "partial" }),
  source({ id: "alanzhang-analytics", name: "alanzhang15/ff-analytics-demo", shortName: "FF Analytics", sourceType: "community_sheet", category: "community", sourceUrl: "https://github.com/alanzhang15/ff-analytics-demo", notes: "Open-source VOR valuation pipeline and live inflation overlay with all three scoring modes.", formats: ["standard", "half_ppr", "ppr"] }),
  source({ id: "bidiron", name: "BIDIRON Auction Simulator", shortName: "BIDIRON", sourceType: "custom_calculator", category: "community", sourceUrl: "https://www.bidirondraft.com/", notes: "Public one-player auction simulator; not a downloadable comparison board." }),
];

const restrictedSources: AuctionValueSource[] = [
  source({ id: "footballguys", name: "Footballguys", shortName: "FBGuys", sourceType: "expert_projection", category: "restricted", sourceUrl: "https://www.footballguys.com/salary-cap-auction-values?pos=all", notes: "Only 15 rows visible in the unauthenticated public preview are imported; full tools require access.", formats: ["ppr"], budget: 200, access: "partial", comparisonReady: true, sourceUpdatedAt: "2026-08-25", importedAt: "2026-08-25T14:16:50.648Z" }),
  source({ id: "ftn", name: "FTN Fantasy", shortName: "FTN", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://ftnfantasy.com/nfl/fantasy-football-auction-values", notes: "Premium fantasy-football auction resource; no restricted rows are imported.", access: "paid" }),
  source({ id: "4for4", name: "4for4", shortName: "4for4", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://www.4for4.com/fantasy-football-draft-kit", notes: "Draft-kit rankings and tools require a subscription.", access: "paid" }),
  source({ id: "establish-the-run", name: "Establish The Run", shortName: "ETR", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://subscribe.establishtherun.com/nfl/", notes: "Premium draft-kit content; no subscriber data is requested.", access: "paid" }),
  source({ id: "playerprofiler", name: "PlayerProfiler", shortName: "PlayerProfiler", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://www.playerprofiler.com/", notes: "Premium rankings and draft tools; no public auction-dollar board is imported.", access: "paid" }),
  source({ id: "pff-plus", name: "PFF+", shortName: "PFF+", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://www.pff.com/fantasy", notes: "Premium fantasy rankings and tools.", access: "paid" }),
  source({ id: "fantasy-alarm", name: "Fantasy Alarm", shortName: "FAlarm", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://www.fantasyalarm.com/fantasy-football-draft-guide", notes: "The current 2026 draft guide includes auction coverage; premium tools require access.", access: "paid" }),
  source({ id: "fantasy-points", name: "FantasyPoints", shortName: "FPoints", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://www.fantasypoints.com/", notes: "Subscriber draft-guide resource; no stable public 2026 auction page was verified.", access: "paid", verificationStatus: "partial" }),
  source({ id: "espn-personalized", name: "ESPN Personalized Dollar Generator", shortName: "ESPN Custom", sourceType: "custom_calculator", category: "restricted", sourceUrl: "https://www.espn.com/fantasy/football/", notes: "Personalized league values require an ESPN account and league context.", access: "registration_required" }),
  source({ id: "rotoballer-premium", name: "RotoBaller Premium Auction Tool", shortName: "RotoBaller", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://www.rotoballer.com/", notes: "Premium auction tools are cataloged, but no stable public 2026 landing page was verified.", access: "paid", verificationStatus: "partial" }),
  source({ id: "fantasy-index", name: "Fantasy Index", shortName: "FIndex", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://fantasyindex.com/", notes: "Paid fantasy-football publication and draft resources.", access: "paid" }),
  source({ id: "the-huddle", name: "The Huddle", shortName: "Huddle", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://tools.thehuddle.com/", notes: "Subscriber fantasy rankings and tools.", access: "paid" }),
  source({ id: "football-diehards", name: "FootballDiehards", shortName: "Diehards", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://www.footballdiehards.com/", notes: "Subscriber draft and season-long fantasy tools.", access: "paid" }),
  source({ id: "fantasydata", name: "FantasyData", shortName: "FantasyData", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://fantasydata.com/fantasy-football-draft-kit", notes: "Commercial data and draft tools; licensed values are not republished.", access: "paid" }),
  source({ id: "rosterwatch", name: "RosterWatch", shortName: "RosterWatch", sourceType: "external_sheet", category: "restricted", sourceUrl: "https://rosterwatch.com/", notes: "Auction cheat-sheet tool is available to PRO members.", access: "paid" }),
];

const archiveSources: AuctionValueSource[] = [
  source({ id: "sgpn-archive", name: "Sports Gambling Podcast Network Historical Auction Sheet", shortName: "SGPN", sourceType: "archive", category: "archive", sourceUrl: "https://www.sportsgamblingpodcast.com/fantasy-football-auction-values/", notes: "Historical article; excluded from the 2026 directory and consensus.", verificationStatus: "archived" }),
  source({ id: "weightliftinglulu-archive", name: "WeightLiftingLulu Historical Sheet", shortName: "WLL", sourceType: "archive", category: "archive", sourceUrl: "https://www.reddit.com/r/fantasyfootball/", notes: "Historical community sheet; a current maintained destination was not verified.", access: "unavailable", verificationStatus: "archived" }),
  source({ id: "sleeper-scraper-archive", name: "Sleeper Auction Price Scraper", shortName: "Sleeper Scraper", sourceType: "archive", category: "archive", sourceUrl: "https://github.com/", notes: "Historical scraper reference; not used because current public auction data requires explicit format assumptions.", access: "unavailable", verificationStatus: "archived" }),
  source({ id: "sporting-news-archive", name: "Sporting News Historical Values", shortName: "Sporting News", sourceType: "archive", category: "archive", sourceUrl: "https://www.sportingnews.com/us/fantasy", notes: "The historical auction article is gone; the current fantasy hub is retained only for attribution.", verificationStatus: "archived" }),
  source({ id: "justin-boone-archive", name: "Justin Boone Historical Yahoo Values", shortName: "Boone", sourceType: "archive", category: "archive", sourceUrl: "https://www.thescore.com/news/", notes: "Historical Yahoo-value reference; no current standalone sheet.", verificationStatus: "archived" }),
  source({ id: "fffaceoff-archive", name: "FFFaceoff Historical AAV", shortName: "FFFaceoff", sourceType: "archive", category: "archive", sourceUrl: "https://fffaceoff.com/fantasy-football-auction-values/", notes: "Historical AAV page retained for attribution only.", verificationStatus: "archived" }),
  source({ id: "boom-outlier-archive", name: "Boom Outlier Historical Sheet", shortName: "Boom", sourceType: "archive", category: "archive", sourceUrl: "https://www.reddit.com/r/fantasyfootball/", notes: "Historical community source; current maintained URL unavailable.", access: "unavailable", verificationStatus: "archived" }),
  source({ id: "pfn-archive", name: "Pro Football Network Historical Auction Values", shortName: "PFN", sourceType: "archive", category: "archive", sourceUrl: "https://www.profootballnetwork.com/fantasy-football-auction-values/", notes: "Historical article retained outside current consensus.", verificationStatus: "archived" }),
  source({ id: "spreadsheet-solving-archive", name: "SpreadsheetSolving Workbook", shortName: "SS Workbook", sourceType: "archive", category: "archive", sourceUrl: "https://spreadsheetsolving.com/a-simple-fantasy-football-auction-draft-spreadsheet/", notes: "2015-era workbook, last revised in 2023; intentionally archived.", verificationStatus: "archived" }),
  source({ id: "thescore-archive", name: "TheScore Historical Values", shortName: "theScore", sourceType: "archive", category: "archive", sourceUrl: "https://www.thescore.com/news/", notes: "Historical fantasy values without a verified current auction board.", verificationStatus: "archived" }),
  source({ id: "pff-auction-archive", name: "Historical PFF Auction Sheet", shortName: "PFF", sourceType: "archive", category: "archive", sourceUrl: "https://www.pff.com/fantasy", notes: "Historical public auction sheet; current product is PFF+ restricted.", verificationStatus: "archived" }),
  source({ id: "rosterwatch-archive", name: "Historical RosterWatch Auction Rankings", shortName: "RosterWatch", sourceType: "archive", category: "archive", sourceUrl: "https://rosterwatch.com/", notes: "Older public rankings archived; current auction tool is member-only.", verificationStatus: "archived" }),
];

export const AUCTION_VALUE_SOURCE_REGISTRY: readonly AuctionValueSource[] = [
  ...currentValueSources,
  ...marketAndToolSources,
  ...communitySources,
  ...restrictedSources,
  ...archiveSources,
];

export const AUCTION_VALUE_SOURCE_BY_ID = new Map(
  AUCTION_VALUE_SOURCE_REGISTRY.map((entry) => [entry.id, entry]),
);
